### ISSUE TITLE
Legend showing issue

### ISSUE THREAD

**Issue by ttsesm** [rgsouthall/vi-suite06#13]
Hi Ryan,

From time to time I am getting the following error, while also I am not able to activate the legend to show the lux values

```
Traceback (most recent call last):
  File "/home/ttsesm/Development/BlenderProc/blender/blender-2.83.2-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 3367, in draw_linum
    self.legend_num.draw(context)
  File "/home/ttsesm/Development/BlenderProc/blender/blender-2.83.2-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 381, in draw
    self.update(context)
  File "/home/ttsesm/Development/BlenderProc/blender/blender-2.83.2-linux64/2.83/scripts/addons/vi-suite06/vi_display.py", line 397, in update
    if ob.data.get('shape_keys') and str(self.fn) in [sk.name for sk in ob.data.shape_keys.key_blocks] and ob.active_shape_key.name != str(self.fn):
ReferenceError: StructRNA of type Object has been removed
```

**Comment by rgsouthall** [comment]
You'll have to tell me what it is you are doing differently to generate this error.

**Comment by ttsesm** [comment]
Well that's a good question, it is a bit random and I am not sure what initiates it. I've tried to replicate it by doing different things but it was not possible. I will try to experiment a bit more and see if I can figure out the cause.

**Comment by ttsesm** [comment]
Closing since I cannot reproduce it again.

**Comment by ttsesm** [comment]
Hi Ryan,

Ok, I found how to reproduce the problem. Steps to follow:

1. Load/create geometry and apply simulation
2. In Layout workspace enable `VI Display --> Radiance Display --> Enable Point visualization`
3. Go to Scripting workspace Right mouse click on the `LiVi Results` in the outliner `--> Delete Hierarchy`
4. Turn around/Zoom in-out the 3d model in the 3D viewport either in the Layout or Scripting workspace and you will get a bunch of such messages 

Hope it helps.

**Comment by rgsouthall** [comment]
Makes sense then. You are deleting results geometry while still
visualising results based on that geometry.

**Comment by ttsesm** [comment]
Well yes you have a point, but I would expect that once I delete the results in the outliner the 3D viewer to be updated and the visualized results and anything that had to do with it to be cleared and removed as well. 

Actually the numbers and the falsecolor layer are removed, but for example the legend icon is stuck there and I do not know if there is something else which I cannot see.

![Screenshot_20201029_150947](https://user-images.githubusercontent.com/10189018/97584958-e0db8a00-19f8-11eb-9ceb-a26a3d859634.png)

**Comment by ttsesm** [comment]
Also to mention that if I do all the steps while working only in one workspace i.e. Layout or Scripting then these messages are not showing and everything seems to be cleared fine both in the outliner and 3D view, but if I jump from one to another it seems to initiate this issue for some reason.
