### ISSUE TITLE
Legend button not visible and error message

### ISSUE THREAD

**Issue by ManiakManiak** [rgsouthall/vi-suite06#17]
Hi Ryan,
I  tried to recreate scenario from youtube tut: VI-Suite v0.4 - Simple Radiance Lighting Analysis. Everything works fine but Im not able to see legend buttom after I click "Radiance Dispaly". Blender gives me this error:
Traceback (most recent call last):
  File "C:\Users\Jerry\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\vi-suite06-master\vi_display.py", line 3314, in invoke
    self.legend = draw_legend(context, svp['liparams']['unit'], self.results_bar.ret_coords(r2w, r2h, 0)[0], r2w, r2h, 125, 400, 20)
  File "C:\Users\Jerry\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\vi-suite06-master\vi_display.py", line 1554, in __init__
    self.update(context)
  File "C:\Users\Jerry\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\vi-suite06-master\vi_display.py", line 1563, in update
    self.cols = retcols(mcm.get_cmap(svp.vi_leg_col), self.levels)
NameError: name 'mcm' is not defined

location: <unknown location>:-1

![Clipboard-20201031-01](https://user-images.githubusercontent.com/18272476/97784609-21c1d300-1ba0-11eb-859e-6df7c34e9b7c.png)

I try reinstal addon (vi-suite06-master.zip) and Radiance. Blender v2.83.8 LTS
Thanks.

**Comment by rgsouthall** [comment]
Does the vi-suite-log file in Blender's text editor say anything?

**Comment by ManiakManiak** [comment]
Just this:
2020-10-31 19:57:43: Running rtrace: rtrace -n 8 -w  -ab 2 -ad 256 -as 128 -aa 0 -dj 0 -ds 0 -dr 1 -ss 0 -st 1 -lw 0.0001 -lr 2  -faa -h -ov -I "C:\Users\Jerry\Desktop\201031_Test01\201031_Test01-1.oct"

**Comment by rgsouthall** [comment]
Looks like Blender's Python installation does not see amy matplotlib installation. What is the version of Python Blender is using and what does putting "import matplotlib" into Blender's Python window say?

**Comment by ManiakManiak** [comment]
PYTHON INTERACTIVE CONSOLE 3.7.4 (default, Feb 17 2020, 16:23:28) [MSC v.1916 64 bit (AMD64)]

Builtin Modules:       bpy, bpy.data, bpy.ops, bpy.props, bpy.types, bpy.context, bpy.utils, bgl, blf, mathutils
Convenience Imports:   from mathutils import *; from math import *
Convenience Variables: C = bpy.context, D = bpy.data

>>> import matplotlib
>>> 
>>>

**Comment by rgsouthall** [comment]
And press enter

**Comment by ManiakManiak** [comment]
:) Yes, I did that. (Githhub translate those symbols...)
![image](https://user-images.githubusercontent.com/18272476/97789630-4c248800-1bc2-11eb-9f38-9af2918326bc.png)

**Comment by rgsouthall** [comment]
Interesting. Try these lines in order.
matplotlib.use('qt5agg', force = True)
import matplotlib.pyplot as plt
import matplotlib.cm as mcm  
import matplotlib.colors as mcolors
from matplotlib.patches import Rectangle
from matplotlib.collections import PatchCollection

**Comment by ManiakManiak** [comment]
>>> import matplotlib
>>> matplotlib.use('qt5agg', force = True)
>>> import matplotlib.pyplot as plt
**Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Users\Jerry\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\vi-suite06-master\Python\win32\matplotlib\pyplot.py", line 2282, in <module>
    switch_backend(rcParams["backend"])
  File "C:\Users\Jerry\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\vi-suite06-master\Python\win32\matplotlib\pyplot.py", line 221, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender2.83LTS_2.83.8.0_x64__ppwjx1n5r4v9t\Blender\2.83\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Jerry\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\vi-suite06-master\Python\win32\matplotlib\backends\backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "C:\Users\Jerry\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\vi-suite06-master\Python\win32\matplotlib\backends\backend_qt5.py", line 15, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "C:\Users\Jerry\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\vi-suite06-master\Python\win32\matplotlib\backends\qt_editor\figureoptions.py", line 12, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File "C:\Users\Jerry\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\vi-suite06-master\Python\win32\matplotlib\backends\qt_compat.py", line 168, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding**

**Comment by rgsouthall** [comment]
And you're on Windows I assume?

**Comment by ManiakManiak** [comment]
Yes

**Comment by rgsouthall** [comment]
I'll look into it.

**Comment by rgsouthall** [comment]
Works fine on my Windows machine.
Can you confirm that you are using latest git zip from master? Try removing the vi-suite from the addons in Blender and then delete the vi-suite directory from the addons folder. Then reinstall the zip via the addons window. Use the Radiance installation that comes with the VI-Suite i.e. do not set a custom Radiance path.

**Comment by ManiakManiak** [comment]
Hi Ryan,
I try uninstal, delete everything. Blender, Radiance, VI-Suite(AppData\Roaming...). Instal Blender 2.83.6 LTS and 
vi-suite06-master.zip. Still same problem. It probably something specifically related to my PC.
I instal VI-Suite on my work PC and everything works fine so Im safe. Thank for you time and effort :).

**Comment by rgsouthall** [comment]
The only thing that comes to mind is that you have an environment variable e.g. PYTHONPATH, which points to another PyQt5 or matplotlib installation on your machine which is not compatible with the some of the included elements in the VI-Suite.

**Comment by rgsouthall** [comment]
In fact I wouldn't mind knowing what
**import os
os.environ['PYTHONPATH']**
reports in Blender's Python console.

**Comment by ManiakManiak** [comment]
![image](https://user-images.githubusercontent.com/18272476/97803745-9a319e00-1c4b-11eb-943d-c41e270e628c.png)

**Comment by rgsouthall** [comment]
Then I am stumped. Pythonpath is right and matplotlib version is right.
