### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by ttsesm** [rgsouthall/vi-suite06#18]
Hi Ryan,

In the attached scene I am getting the following error:

```
Error: Traceback (most recent call last):
  File "/home/ttsesm/Development/blender-2.83.2-linux64/2.83/scripts/addons/vi-suite06/vi_operators.py", line 1002, in invoke
    calcout = li_calc(self, simnode, livisimacc(simnode))
  File "/home/ttsesm/Development/blender-2.83.2-linux64/2.83/scripts/addons/vi-suite06/livi_calc.py", line 122, in li_calc
    bccout = ovp.basiccalcapply(scene, frames, rtcmds, simnode, curres, pfile)
  File "/home/ttsesm/Development/blender-2.83.2-linux64/2.83/scripts/addons/vi-suite06/livi_func.py", line 422, in basiccalcapply
    sareas[ai] = sum([rareas[gi]/totarea for gi in range(len(rgeom)) if ais[gi] == ai])
  File "/home/ttsesm/Development//blender-2.83.2-linux64/2.83/scripts/addons/vi-suite06/livi_func.py", line 422, in <listcomp>
    sareas[ai] = sum([rareas[gi]/totarea for gi in range(len(rgeom)) if ais[gi] == ai])
ZeroDivisionError: float division by zero
```

I am not sure though whether it is scene related or a bug.

[house.zip](https://github.com/rgsouthall/vi-suite06/files/5481259/house.zip)

**Comment by rgsouthall** [comment]
Both. Incorrect geometry is now returning zero area as per the previous fix, which causes this error. It is fixed but I won't be uploading to github for a few days. For now change the offending line to:
sareas[ai] = sum([rareas[gi]/totarea for gi in range(len(rgeom)) if ais[gi] == ai]) if totarea else 0

**Comment by ttsesm** [comment]
I see, thanks.

**Comment by ttsesm** [comment]
Addressed in commit https://github.com/rgsouthall/vi-suite06/commit/19f4be8956a4a5df6c0c07bb96501d077c497d69
