### ISSUE TITLE
Netgen not found

### ISSUE THREAD

**Issue by SergioBini** [rgsouthall/vi-suite06#28]
In PoP Os 20.04 (Ubuntu 20.04)
Netgen not found in node editor when adding the Flovi NetGen Process Node

Blender 2.83.13
Paraview V8
VI-Suit 0.6 latest

**Comment by rgsouthall** [comment]
I'm going to need a bit more information than that Sergio.
Is Blender using a built-in Python installation. What version of Python is it seeing? What does the terminal output say and/or the vi-suite-log file in the text editor?

**Comment by SergioBini** [comment]
Blender 2.83 LTS v.13 from a tar.bz by Blender site Download section
No Blender trough ppt, but there is a standalone version of Blender 2.92 trough flatpack
When adding the FloVi Netgen Process Node there's no messages return in the text editor.
The system's version of python is 2.7.18, and here is the message I get in the Python console when asking to print the path, maybe could be useful:
![screenshot_1](https://user-images.githubusercontent.com/81572957/112950105-36e46300-913a-11eb-9ce9-70d48a4981f9.png)

>>> print(sys.path)
['/home/sergiobini/blender-2.83.13-linux64/2.83/scripts/startup', '/home/sergiobini/blender-2.83.13-linux64/2.83/scripts/modules', '/home/sergiobini/blender-2.83.13-linux64/2.83/python/lib/python37.zip', '/home/sergiobini/blender-2.83.13-linux64/2.83/python/lib/python3.7', '/home/sergiobini/blender-2.83.13-linux64/2.83/python/lib/python3.7/lib-dynload', '/home/sergiobini/blender-2.83.13-linux64/2.83/python/lib/python3.7/site-packages', '/home/sergiobini/blender-2.83.13-linux64/2.83/scripts/freestyle/modules', '/home/sergiobini/blender-2.83.13-linux64/2.83/scripts/addons/modules', '/home/sergiobini/.config/blender/2.83/scripts/addons/modules', '/home/sergiobini/blender-2.83.13-linux64/2.83/scripts/addons', '/home/sergiobini/.config/blender/2.83/scripts/addons', '/home/sergiobini/.config/blender/2.83/scripts/addons/vi-suite06-master/Python/linux', '/opt/openfoam8/bin']

I also have a FreeCAD version (0.19 daily) installed trough ppa repository, maybe it causes some interactions (I read somewhere that it's possible in some cases)

**Comment by rgsouthall** [comment]
You should get an error in the terminal when starting up Blender from the
command line. What does that say?

**Comment by SergioBini** [comment]
This is what i get starting from command line:

~/blender-2.83.13-linux64$ ./blender
Read prefs: /home/sergiobini/.config/blender/2.83/config/userpref.blend
found bundled python: /home/sergiobini/blender-2.83.13-linux64/2.83/python
libnglib.so: cannot open shared object file: No such file or directory
libnglib.so: cannot open shared object file: No such file or directory
Warning: class No_En_Con contains a property which should be an annotation!
/home/sergiobini/.config/blender/2.83/scripts/addons/vi-suite06-master/__init__.py:656
    assign as a type annotation: No_En_Con.resaws
    assign as a type annotation: No_En_Con.resawd
    assign as a type annotation: No_En_Con.resah
    assign as a type annotation: No_En_Con.resasm
    assign as a type annotation: No_En_Con.restt
    assign as a type annotation: No_En_Con.resh
    assign as a type annotation: No_En_Con.restwh
    assign as a type annotation: No_En_Con.restwc
    assign as a type annotation: No_En_Con.reswsg
    assign as a type annotation: No_En_Con.rescpp
    assign as a type annotation: No_En_Con.rescpm
    assign as a type annotation: No_En_Con.resvls
    assign as a type annotation: No_En_Con.resvmh
    assign as a type annotation: No_En_Con.resim
    assign as a type annotation: No_En_Con.resiach
    assign as a type annotation: No_En_Con.resco2
    assign as a type annotation: No_En_Con.resihl
    assign as a type annotation: No_En_Con.resl12ms
    assign as a type annotation: No_En_Con.reslof
    assign as a type annotation: No_En_Con.resmrt
    assign as a type annotation: No_En_Con.resocc
    assign as a type annotation: No_En_Con.resfhb
    assign as a type annotation: No_En_Con.ressah
    assign as a type annotation: No_En_Con.ressac
    assign as a type annotation: No_En_Con.reshrhw
    assign as a type annotation: No_En_Con.restcvf
    assign as a type annotation: No_En_Con.restcmf
    assign as a type annotation: No_En_Con.restcot
    assign as a type annotation: No_En_Con.restchl
    assign as a type annotation: No_En_Con.restchg
    assign as a type annotation: No_En_Con.restcv
    assign as a type annotation: No_En_Con.restcm
    assign as a type annotation: No_En_Con.resldp
    assign as a type annotation: No_En_Con.resoeg
    assign as a type annotation: No_En_Con.respve
    assign as a type annotation: No_En_Con.respvw
    assign as a type annotation: No_En_Con.respvt
    assign as a type annotation: No_En_Con.respveff
Warning: class No_En_Net_Sched contains a property which should be an annotation!
/home/sergiobini/.config/blender/2.83/scripts/addons/vi-suite06-master/__init__.py:656
    assign as a type annotation: No_En_Net_Sched.u1
    assign as a type annotation: No_En_Net_Sched.u2
    assign as a type annotation: No_En_Net_Sched.u3
    assign as a type annotation: No_En_Net_Sched.u4
    assign as a type annotation: No_En_Net_Sched.f1
    assign as a type annotation: No_En_Net_Sched.f2
    assign as a type annotation: No_En_Net_Sched.f3
    assign as a type annotation: No_En_Net_Sched.f4
    assign as a type annotation: No_En_Net_Sched.t1
    assign as a type annotation: No_En_Net_Sched.t2
    assign as a type annotation: No_En_Net_Sched.t3
    assign as a type annotation: No_En_Net_Sched.t4
Warning: class No_En_Net_SSFlow contains a property which should be an annotation!
/home/sergiobini/.config/blender/2.83/scripts/addons/vi-suite06-master/__init__.py:656
    assign as a type annotation: No_En_Net_SSFlow.sfof4
Warning: class No_En_Mat_Sched contains a property which should be an annotation!
/home/sergiobini/.config/blender/2.83/scripts/addons/vi-suite06-master/__init__.py:656
    assign as a type annotation: No_En_Mat_Sched.u1
    assign as a type annotation: No_En_Mat_Sched.u2
    assign as a type annotation: No_En_Mat_Sched.u3
    assign as a type annotation: No_En_Mat_Sched.u4
    assign as a type annotation: No_En_Mat_Sched.f1
    assign as a type annotation: No_En_Mat_Sched.f2
    assign as a type annotation: No_En_Mat_Sched.f3
    assign as a type annotation: No_En_Mat_Sched.f4
    assign as a type annotation: No_En_Mat_Sched.t1
    assign as a type annotation: No_En_Mat_Sched.t2
    assign as a type annotation: No_En_Mat_Sched.t3
    assign as a type annotation: No_En_Mat_Sched.t4
OpenColorIO Error: The specified transform file '/home/sergiobini/blender-2.83.13-linux64/2.83/datafiles/colormanagement/luts/srgb_inv.spi1d' could not be loaded. Invalid 'From' Tag

**Comment by rgsouthall** [comment]
That's more useful. Does a libnglib.so file exist in the vi-suite06/Python/linux addon folder and if so how big is it?

**Comment by SergioBini** [comment]
yes it does exist and it's 204,3 kB

**Comment by rgsouthall** [comment]
Hmm. The plot thickens. If you enter
import os
os.environ['LD_LIBRARY_PATH'] 
in Blender's python console what does it say?

**Comment by SergioBini** [comment]
it say
>>> import os
>>> os.environ['LD_LIBRARY_PATH']

'/home/sergio/.config/blender/2.83/scripts/addons/vi-suite06-master/Python/linux'

>>>

**Comment by rgsouthall** [comment]
That looks right. I'm running out of ideas. So 
import netgen
in the python console flags up missing libnglib.so problem too?

**Comment by SergioBini** [comment]
this is the report
>>> import netgen
Traceback (most recent call last):
  File "/home/sergio/blender-2.83.13-linux64/2.83/python/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<blender_console>", line 1, in <module>
  File "/home/sergio/.config/blender/2.83/scripts/addons/vi-suite06-master/Python/linux/netgen/__init__.py", line 16, in <module>
    from . import libngpy
ImportError: libnglib.so: impossibile aprire il file oggetto condiviso: File o directory non esistente

**Comment by rgsouthall** [comment]
Try moving the libnglib.so file to the netgen folder
in vi-suite06-master/Python/linux/

**Comment by SergioBini** [comment]
I tried to copy the file in /vi-suite06-master/Python/linux/ but it's still not working.
But I noticed that my vi-suite06-master addon is in /.config/blender 2.83/scripts/addons/vi-suite-master, that's I think it's ok, but in this folder ther's the OFFiles folder and it hosts a linux/lib/ folders and there's an other libnglib.so into.  This file is 136,8 kb while the file with the same name in Pyhton/linux folder is 204,3 kB as said previously.. Does it mean something?

**Comment by rgsouthall** [comment]
Shouldn't do. That OFFiles directory is obsolete as I no longer plan to
bundle OpenFOAM with the Vi-Suite.
Not sure what the problem is. A friend runs Ubuntu and I'll see if I can
use his machine to debug.

**Comment by Morrat** [comment]
I am having the same problem. Did you discover a solution?

**Comment by rgsouthall** [comment]
I haven't had a chance to get in front of an Ubuntu machine yet. Are you on Ubuntu as well?

**Comment by Morrat** [comment]
Yes, I installed Ubuntu 20.04 clean on a machine to try it out. I am not very experienced in using Linux.
I've actually tried a couple of times in the past months in case there was something I left out during installation, but I haven't gotten it to work at all.

I am using Blender 2.83.15 LTS, OpenFOAM v8

All the other components works fine.
It would be helpful to know the exact installation process I guess. If the location of the referenced plugin matters, or if there is a difference in Blender depending on how you install it, since there are so many different ways to do it.
I am basically receiving the same errors as @SergioBini 

I would also like to add that I have tried to run it on both VM and physical machines.

**Comment by ZeusNJ** [comment]
Hi all,
Despite it is a little old post, did you manage to find a solution for this? I'm facing the same issue.

**Comment by Morrat** [comment]
Hi @ZeusNJ 

Sadly I didn't, I tried all different sort of configurations, both using Ubuntu and ArchLinux, but kept getting the NetGen not found error.
Although I managed to run the OpenFoam example simulations.

**Comment by ZeusNJ** [comment]
Hi @Morrat ,

How is that so? How did you manage to mesh your case if netgen is not working? I'm deeply interested since I'm trying to insert snappyHexMesh into this addon but firstly I wanted to know how it works. Could you be more specific about how did you managed to run your simulation?

Thanks in advance
