### ISSUE TITLE
Activation issue

### ISSUE THREAD

**Issue by SyedShaQutub** [rgsouthall/vi-suite06#3]
Hello @rgsouthall 

Thank you for the great API and also for the latest release to blender 2.8. I have a trivial issue in activating the suite in the blender 2.82. Although I copy the folder into addon and then enable it, the vi suite display panel is not showing anything except the heading. Am I missing any step in between?
vi suite version: 0.6

warnings shown in system console of blender:
Warning: class No_En_Geo contains a property which should be an annotation!
/home/qwert/.config/blender/2.82/scripts/addons/vi-suite06-master/__init__.py:524
    assign as a type annotation: No_En_Geo.geo_offset
Warning: class No_En_Con contains a property which should be an annotation!
/home/qwert/.config/blender/2.82/scripts/addons/vi-suite06-master/__init__.py:524
    assign as a type annotation: No_En_Con.resaam
    assign as a type annotation: No_En_Con.resaws
    assign as a type annotation: No_En_Con.resawd
    ......

**Comment by SyedShaQutub** [comment]
Hello again,

After a few changes, now I get the render display button but not all the options are shown as in your tutorials. 
Also, I have a few changes to report on blender 2.82

a. vi_func.py
line 1304: return([o for o in validobs if o.type == 'MESH' and o.data.materials and not (o.parent and os.path.isfile(o.ies_name)) and o.vi_params.vi_type not in ('4', '5') \
o.ies_name attribute is missing. 

Temporary solution: Not sure about the purpose of the check. For now, I have commented it out and the export geometry works.

b. livi_func.py
After livi simulation computation, if I click on radiance display I get this error


Error: Traceback (most recent call last):
  File "/home/qwert/.config/blender/2.82/scripts/addons/vi-suite06-master/vi_display.py", line 4009, in invoke
    if li_display(self, self.simnode) == 'CANCELLED':
  File "/home/qwert/.config/blender/2.82/scripts/addons/vi-suite06-master/vi_display.py", line 191, in li_display
    setscenelivivals(scene)
  File "/home/qwert/.config/blender/2.82/scripts/addons/vi-suite06-master/livi_func.py", line 79, in setscenelivivals
    unit = udict[svp.li_disp_menu]


Thank you in advance for your help :)

**Comment by Sinasta** [comment]
I get the same errors after livi simulation. did you found a solution?

**Comment by SyedShaQutub** [comment]
> I get the same errors after livi simulation. did you found a solution?

No; Still waiting for @rgsouthall's reply

**Comment by rgsouthall** [comment]
Hi.
The 2.8 version has not been released yet and is still a WIP.
I wil post on the blog when I have it all more or less working.
Cheers
Ryan

**Comment by Sinasta** [comment]
Perfect. thank you very much for your work @rgsouthall ! If you need any testers please feel free to contact me.
