### ISSUE TITLE
photon mapping calculation error

### ISSUE THREAD

**Issue by ttsesm** [rgsouthall/vi-suite06#7]
Hi @rgsouthall I've tried to apply some photonmapping calculation but the operation seems to get stuck with the following output:

```
Traceback (most recent call last):
  File "/home/ttsesm/.config/blender/2.83/scripts/addons/vi-suite06/vi_operators.py", line 999, in invoke
    calcout = li_calc(self, simnode, livisimacc(simnode))
  File "/home/ttsesm/.config/blender/2.83/scripts/addons/vi-suite06/livi_calc.py", line 64, in li_calc
    pmrun = Popen(shlex.split(pmcmd), stderr = PIPE, stdout = PIPE)
NameError: name 'shlex' is not defined

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "/home/ttsesm/.config/blender/2.83/scripts/addons/vi-suite06/vi_operators.py", line 999, in invoke
    calcout = li_calc(self, simnode, livisimacc(simnode))
  File "/home/ttsesm/.config/blender/2.83/scripts/addons/vi-suite06/livi_calc.py", line 64, in li_calc
    pmrun = Popen(shlex.split(pmcmd), stderr = PIPE, stdout = PIPE)
NameError: name 'shlex' is not defined

location: <unknown location>:-1


[INFO   ] [Logger      ] Record log in /home/ttsesm/.kivy/logs/kivy_20-10-01_11.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/home/ttsesm/.config/blender/2.83/scripts/addons/vi-suite06/Python/linux/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.4 (default, Oct  8 2019, 15:23:02) 
[GCC 6.3.1 20170216 (Red Hat 6.3.1-3)]
[INFO   ] [Python      ] Interpreter at "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/python/bin/python3.7m"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 455.23.04'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 1080/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
```

![image](https://user-images.githubusercontent.com/10189018/94819946-2c9e1200-0400-11eb-8ca8-3a17d8e76e04.png)

System info:
OS: Archlinux 5.8.10-arch1-1
Blender: 2.83 (downloaded from the official website)

**Comment by rgsouthall** [comment]
Thanks for the bug report.
This is now fixed in git.

**Comment by ttsesm** [comment]
I'll test it on my side ASAP and confirm.

**Comment by ttsesm** [comment]
@rgsouthall the previous error seems to be fixed but now I am getting the following output on `Calculate`:

`fatal - proc 5: too many prepasses, no global photons stored`

`Preview` seems to work though, any idea what could be the cause?

Also I've noticed that after I install the add-on I have to manually set the binaries in `/RadFiles/linux/bin/` as executables otherwise I am getting permission errors e.g. `PermissionError: [Errno 13] Permission denied: 'oconv'` is that normal?

**Comment by ttsesm** [comment]
Ok apparently both errors are not related with the addon per se. 

It seems that the first one has to do with the scene and its materials, thus a radiance related issue. 

Regarding the permission error seems to be related with how blender installs the addon. If I just copy the extracted folder into the `scripts/addons/` folder and then just activate it from the `Preferences --> Addons` from within Blender then the permissions are fine.

Thus, I think I can close this issue as well.
