### ISSUE TITLE
calculation error if vertices is selected as result point

### ISSUE THREAD

**Issue by ttsesm** [rgsouthall/vi-suite06#9]
Hi @rgsouthall,

When I select vertices as a result calculation point in the geometry process node and then try to calculate in the simulation node I am getting the following error while calculation is stuck:

```
[INFO   ] [Logger      ] Record log in /home/ttsesm/.kivy/logs/kivy_20-10-09_7.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/Python/linux/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.4 (default, Oct  8 2019, 15:23:02) 
[GCC 6.3.1 20170216 (Red Hat 6.3.1-3)]
[INFO   ] [Python      ] Interpreter at "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/python/bin/python3.7m"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 455.23.04'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 1080/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[[0.5665826 0.5665826 0.5665826]
 [0.5681754 0.5672536 0.5673093]
 [0.5685138 0.5673961 0.5674637]
 ...
 [0.262754  0.1106851 0.1198815]
 [1.23062   1.229004  1.229101 ]
 [0.6112098 0.6112098 0.6112098]]
Traceback (most recent call last):
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_operators.py", line 999, in invoke
    calcout = li_calc(self, simnode, livisimacc(simnode))
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/livi_calc.py", line 122, in li_calc
    bccout = ovp.basiccalcapply(scene, frames, rtcmds, simnode, curres, pfile)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/livi_func.py", line 352, in basiccalcapply
    gp[virradres] = (virradm2[gi] * gp.calc_area()).astype(float32)
AttributeError: 'BMVert' object has no attribute 'calc_area'

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/vi_operators.py", line 999, in invoke
    calcout = li_calc(self, simnode, livisimacc(simnode))
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/livi_calc.py", line 122, in li_calc
    bccout = ovp.basiccalcapply(scene, frames, rtcmds, simnode, curres, pfile)
  File "/home/ttsesm/Downloads/blender-2.83.6-linux64/2.83/scripts/addons/vi-suite06/livi_func.py", line 352, in basiccalcapply
    gp[virradres] = (virradm2[gi] * gp.calc_area()).astype(float32)
AttributeError: 'BMVert' object has no attribute 'calc_area'

location: <unknown location>:-1


[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
```

**Comment by rgsouthall** [comment]
Thanks for the bug report. This should now be fixed in git.

**Comment by ttsesm** [comment]
Thanks @rgsouthall.

I confirm that this issue is solved.
